### ISSUE TITLE
Display Size Limitations?

### ISSUE THREAD

**Issue by JimPowersDFL** [fuel9/DisplayMonkey#116]
Hello,

We are working on a display wall project. We will likely settle on a single 98" display for various reasons. Is there a max size that DM can handle? We are looking to have some full screen images but at other times, split it into four separate images. I feel like this should work but wanted to get your feedback before we spend the money.

**Comment by JimPowersDFL** [comment]
Adding to this question, the display we have been quoted is a 4K 98" display. Will we be able to use DM for this particular display wall?

**Comment by psined1** [comment]
Hi, DM puts no limitations as far as size of any particular display really. It relies on internet browser to render canvases. DM has a large set of supported browsers and devices. So, any display should do just fine, as long as computer graphics of your own choosing running a DM terminal will support the resolution of your TV. If you are planning to use TV's built-in internet browser widget to present DM canvases, you might want to test it separately, as there may be other limitations, like JS, video formats support, etc. I'd recommend you rent a TV and test before committing to a large purchase. Hope this helps.

**Comment by JimPowersDFL** [comment]
Thank you. I'll recommend a rental to the folks that write the checks.
