### ISSUE TITLE
Signing into DisplayMonkey_Management

### ISSUE THREAD

**Issue by goat1398** [fuel9/DisplayMonkey#117]
Hi, I can't quite figure out what credentials to use to sign into the management portal.

![dm_console](https://user-images.githubusercontent.com/39496076/57726344-dc51d300-7697-11e9-97eb-6bd06e7d3f19.png)

**Comment by michaelmalmgren** [comment]
Hi there,

Go to the folder where the DMM is installed e.g. c:\inetpub\DisplayMonkey_Managment right click and select the security. Add yourself or a group that you belong to. From the browser, you should then be able to login using domain\user and password.
