### ISSUE TITLE
hiding browser URL bar 

### ISSUE THREAD

**Issue by tenggara** [fuel9/DisplayMonkey#126]
Hello,

I just started with DM today, testing around with notebook as presentation terminal. How do I make a full screen display hiding the browser URL bar? I can set in DM management to hide scroll bar.

thank you in advance

**Comment by michaelmalmgren** [comment]
Hi there, full screen (or kiosk mode) is a feature in your browser so if you search for full screen or kiosk mode in combination with the name of the browser you are using you should be able to find out how. 

For exampel, this is how to start an instance of Chrome in kiosk mode in Windows:

"c:\progra~2\Google\Chrome\Application\chrome.exe" --chrome-frame --kiosk http://localhost/apps/DisplayMonkey/

**Comment by tenggara** [comment]
Thank you very much Michael. it helped. I also found that pressing control+command+f on chrome (macos) will change it to kiosk mode
