### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by FastSlug** [fuel9/DisplayMonkey#129]
Hi, i`m trying to install Display Monkey, I`m running DisplayMonkey_Management, but when I try to load the application I get the following  message:

The resource cannot be found. 
  Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable.  Please review the following URL and make sure that it is spelled correctly. 

 Requested URL: /DisplayMonkey/Account/Login.aspx
![DISPMONKEY](https://user-images.githubusercontent.com/53177342/61628788-f3aacf00-ac8b-11e9-8aa7-86dafa5c2b08.png)

I`m running Server 2012 r2 with sql 2014 express
Can you help me on this error?

**Comment by michaelmalmgren** [comment]
Hi there!
There is no login.aspx page in DM so I suspect that you are trying to open an incorrect URL or that you have not enabled anonymous access to DM in addition to windows authentication. 

![image](https://user-images.githubusercontent.com/25671627/61642587-78ecae80-aca1-11e9-93e1-45a7e9e873e5.png)

**Comment by FastSlug** [comment]
Thank you, I got it working
