### ISSUE TITLE
Power BI Dashboard Tiles

### ISSUE THREAD

**Issue by invicta0** [fuel9/DisplayMonkey#133]
I am attempting to add a Power BI dashboard tile to a panel.  When i configure the new Power BI frame I receive the following error:

Source | Powerbi/Create
Message | The field Visualization URL must be a string or array type with a maximum length of '200'.

**Comment by invicta0** [comment]
Apologies, missed a closed issue when searching for this.

**Comment by michaelmalmgren** [comment]
Are you running version 1.6.1.189 of DM? We had an issue in this area some time ago that was fixed March.

**Comment by invicta0** [comment]
Hi Michael.  I followed the chain of duplicates and found the fix in the latest release.  I have now upgraded our installation and can confirm this is working.
