### ISSUE TITLE
Exchange erro

### ISSUE THREAD

**Issue by covali** [fuel9/DisplayMonkey#15]
Hi,

I am getting below messages while connecting to exchange server account. what can be the reason? do you have an idea?

Regards,

Error:	Server error
Where:	Outlook::callBack::onSuccess
When:	2017-03-10T09:02:30+03:00
Info:	{Error:Object already exists.\\r\\n,Data:{FrameId:1398,PanelId:117,DisplayId:41,Culture:}}

**Comment by DisplayMonkey** [comment]
Hi, we have just released an update 1.4.0. Please upgrade and see if it will take care of your issue.

**Comment by DisplayMonkey** [comment]
It seems your error may be due to an older DM application version, which came before a fix to RSA container lookup was released. See if you can upgrade to the latest version. Are you running DM on-prem or in the cloud? Please provide more details about your setup.

**Comment by DisplayMonkey** [comment]
We have also identified that similar error may take place when you do not specify all settings in the Location hierarchy, such as Culture, Date and Time format. Please see if you can play with these settings to resolve your issue.

**Comment by DisplayMonkey** [comment]
Hi, please advise if the previous suggested remedy has worked for you. Thanks you.

**Comment by covali** [comment]
Hi

now I am getting " Could not be resolved." while creating exchange account after filling the location fields and upgrade the 1.4 version.

any idea?

regards,

**Comment by DisplayMonkey** [comment]
Sounds like you are referring to another issue (#16) which you have opened?

**Comment by DisplayMonkey** [comment]
We are going to close this one as partially addressed/duplicate.
