### ISSUE TITLE
Exchange EWS error

### ISSUE THREAD

**Issue by covali** [fuel9/DisplayMonkey#16]
Hi

I am getting "Exchange Web Services are not currently available for this request because none of the Client Access Servers in the destination site could process the request." error while connecting to EWS. but normally I can connect from https://domain.com/EWS/service.aspx directly with the same username and password. what can be the reason?

regards,

**Comment by DisplayMonkey** [comment]
Hi, we have just released an update 1.4.0. Please upgrade and see if it will take care of your issue.

**Comment by covali** [comment]
Hi

I hev recently upgraded to new version but now it says "Couldn't resolve". As I said before I can login and get the xml file over web with the same username and password. where can I look to the logs to analyze the issue?

regards,

**Comment by DisplayMonkey** [comment]
Hi, it's hard to tell what the real issue is, because it may come from EWS setup. There is an application setting in DMM where you can specify full path for the log file which will receive transcript of EWS handshake when you attempt to connect. It might help shed some light.

Also, albeit optional, when you register EWS account record in DMM see if you enter a "EWS Url (optional)" value. This is useful when EWS auto discovery is not fully setup in your organization. For example, an entry for Outlook 365 would look something like: "https://outlook.office365.com/EWS/Exchange.asmx". If you do not specify a value both DMM and DMP applications will attempt to autoresolve EWS service endpoint address on every call to it based on specified account email address.

**Comment by DisplayMonkey** [comment]
Hi, please advise if the previous suggested remedy has worked for you. Thanks you.

**Comment by DisplayMonkey** [comment]
Have you tried following our suggestion to activate the trace file and see what is in there?

**Comment by covali** [comment]
Hi,

I wrote the whole entry of the Ews server and I can go in that address over web and see the xml file. How can I activate the trace file and see the those logs?

regards,

**Comment by DisplayMonkey** [comment]
Please read up in this thread for our suggestion on how to activate the trace file.

**Comment by covali** [comment]
Hi

below is the trace result

"<Trace Tag="EwsResponse" Tid="57" Time="2017-05-16 17:36:33Z" Version="15.00.0847.030">
  <?xml version="1.0" encoding="utf-8"?>
  <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
      <h:ServerVersionInfo MajorVersion="15" MinorVersion="0" MajorBuildNumber="1263" MinorBuildNumber="5" Version="V2_23" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />
    </s:Header>
    <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <m:ResolveNamesResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
        <m:ResponseMessages>
          <m:ResolveNamesResponseMessage ResponseClass="Error">
            <m:MessageText>No results were found.</m:MessageText>
            <m:ResponseCode>ErrorNameResolutionNoResults</m:ResponseCode>
            <m:DescriptiveLinkKey>0</m:DescriptiveLinkKey>
          </m:ResolveNamesResponseMessage>
        </m:ResponseMessages>
      </m:ResolveNamesResponse>
    </s:Body>
  </s:Envelope>
</Trace>"

regards,

**Comment by DisplayMonkey** [comment]
Well, sounds like your handshake with EWS succeeds indeed. It's probably the mailbox address which you specify that EWS cannot resolve.

We cannot help you here unfortunately. From this point you might want to either take this up with the Exchange team in your organization or try self-support by googling "ErrorNameResolutionNoResults".

**Comment by DisplayMonkey** [comment]
Consider this scenario - you are trying to resolve a mailbox for a valid Outlook contact which has no mailbox/calendar resources associated with in the Exchange repository.

**Comment by DisplayMonkey** [comment]
Closing this post. According to logs above this is not a DM issue.
