### ISSUE TITLE
SSL? Is this possible??

### ISSUE THREAD

**Issue by djstevematthews** [fuel9/DisplayMonkey#162]
Hi we have concern that its not secure web traffic on our network. So looking to convert it to https. Can this be done easily or is there some scripting that needs editing for it to work?

**Comment by psined1** [comment]
HTTPS by itself is a protocol you can activate on your web server, this is just a configuration. But you need a certificate to enable SSL. Certificates can be either self-signed or come from CA. Hope this help. Find more [here](https://support.microsoft.com/en-us/help/324069/how-to-set-up-an-https-service-in-iis). Hope it helps.
