### ISSUE TITLE
High bandwidth usage

### ISSUE THREAD

**Issue by scott-oit** [fuel9/DisplayMonkey#163]
I noticed that our network usage is abnormally high on our display machines. Or windows box is no less than 1 TB a day while our pies are around 750 GB to 1 TB. 

We have 1 Windows box (ethernet) and 3 Pi's (wireless) setup to display the same canvas. We display pictures and no videos. None of our slides are above 4 Mb and most around around 1 Mb. I believe all of these devices are running Chrome. They all restart nightly.

I did some searching but I couldn't find any settings related to cache on the management side. Do you have any suggestions to lower network usage?

**Comment by michaelmalmgren** [comment]
Hi Scott, you will find caching settings under Setup – Other – Application Settings.

**Comment by scott-oit** [comment]
Awesome, thanks so much. I somehow missed those settings.
