### ISSUE TITLE
Problem on IPad 

### ISSUE THREAD

**Issue by philipasbergswenneke** [fuel9/DisplayMonkey#169]
Hi! im trying to run DisplayMonkey on an Ipad 11. it runs fine in Safari but after a few hours the screen turns all white. Google Chrome works but it is zoomed in so only half the content is showing and i dont know how to fix it. It is running PowerBI reports. Any tips ?

**Comment by michaelmalmgren** [comment]
Hi Philip, were you able to figure out what was going on? I would appreciate if you could share your insights.
