### ISSUE TITLE
Error on initial launch

### ISSUE THREAD

**Issue by cjordan19671** [fuel9/DisplayMonkey#172]
I have checked an rechecked but I am definitely missing something in the setup.  See attached file.

This is a 2012 r2 with 2014 sql express one.  I have installed it 4 times.   I think it is having a problem with the database connection... Any suggestions would be appreciated
![dm](https://user-images.githubusercontent.com/61209025/74954914-7a15c380-53c9-11ea-89e7-bd782478e1d9.png)

**Comment by cjordan19671** [comment]
resolved was database issue

**Comment by michaelmalmgren** [comment]
thanks for letting us now!
