### ISSUE TITLE
Power BI Gateway

### ISSUE THREAD

**Issue by thadspencer** [fuel9/DisplayMonkey#18]
Hi DM, 

I switched one of my Power BI datasets to use an Enterprise Gateway and now get a "filterError" on DM, instead of my tile:

![image](https://cloud.githubusercontent.com/assets/25667119/26114705/e5f0c0a4-3a55-11e7-827f-d7a8934b0e48.png)

I'm running v.1.4.0.145, local windows server.

Thanks,

Thad

**Comment by thadspencer** [comment]
Fixed it, my bad sorry! 

The Azure account I use for DM needed a **Power BI Pro** Licence (well... 60 day trial!)

U gotta have Pro to use a Gateway.... [https://powerbi.microsoft.com/en-us/documentation/powerbi-power-bi-pro-content-what-is-it/](url)

**Comment by DisplayMonkey** [comment]
Hi Thad, this error appears being reported from Power BI API tile loaded event.. I'm afraid this is beyond our reach. I've googled around and found an open [forum thread](http://community.powerbi.com/t5/Integrations-with-Files-and/Embedded-tiles-filtering-problem/td-p/22505) for a similar issue. Have you tried embedding your tile anywhere outside DM, like Excel? Have you tried creating a brand new report off of the new datasource, then a brand new tile off of that report, place it on a brand new dashboard and then try hooking up DM to it? In any case you can try reporting it to MSFT.

**Comment by DisplayMonkey** [comment]
oh well, never mind - didn't see your last comment
