### ISSUE TITLE
Unable to decode image- SSRS

### ISSUE THREAD

**Issue by dan508** [fuel9/DisplayMonkey#182]
Hi all. Having an issue with displaying a SSRS report on the site. It's all configured, and on the mgmt side, I can see that it's working ok (It returns a thumbnail image under 'Change Displayed'), however on the user side, I get a little 'X' where the image should be. This occurs in Chrome, Edge and IE 11.
Opening the console in IE, I see the following errors:
![image](https://user-images.githubusercontent.com/66793648/84681474-12f9bd00-af2c-11ea-82cd-7113f26798a7.png)

Any idea what the issue is?

**Comment by psined1** [comment]
Hi, check out this thread, perhaps your solution is here -
https://stackoverflow.com/questions/27934411/images-failing-to-load-in-ie-with-dom-7009-error-unable-to-decode-in-console

**Comment by dan508** [comment]
hi @psined1. I'm afraid that solution doesn't seem to be the case. Running the debugger in Chrome, it shows the following. Does this help at all?
![image](https://user-images.githubusercontent.com/66793648/84903020-76f3c100-b0a5-11ea-9a85-5ed3a055ca7c.png)

**Comment by psined1** [comment]
Copy that URL from the debug console and open it in a separate browser tab, then check the debug console for any errors.

**Comment by dan508** [comment]
@psined1 
![image](https://user-images.githubusercontent.com/66793648/84915644-fb9a0b80-b0b4-11ea-996f-42ce5557bc91.png)

**Comment by dan508** [comment]
Doesn't return anything, @psined1 
![image](https://user-images.githubusercontent.com/66793648/84917180-e8883b00-b0b6-11ea-91dc-ae8174cd82ab.png)

**Comment by dan508** [comment]
Well guys, I've tried! Can't get this working so we're moving away from DisplayMonkey next week!

**Comment by dan508** [comment]
WEll, not sure what happened but I've reinstalled everything from scratch and it's working now!
