### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jgitau** [fuel9/DisplayMonkey#21]
I am having installation issues on server 2012 R2  with SQL express 2014. Are there any known issues as I can't load the management interface (displaymonkey_management? I get a runtime error ...

**Comment by DisplayMonkey** [comment]
Hi, welcome to DisplayMonkey!

While our team resources are limited and we cannot offer a full-fledged technical support (especially one for free :) - we are open to all feedback we can receive from the community. Providing more details about your issue, such as error specifics, DM version, cloud vs. on-prem, would help us point you in the right direction.

Thanks!

**Comment by DisplayMonkey** [comment]
the OP has not responded for 2 weeks, no error details were provided, issue closed
