### ISSUE TITLE
Quick Book and Event Label

### ISSUE THREAD

**Issue by jaschrock** [fuel9/DisplayMonkey#26]
Is there a way to change what is put in as the event label with a quick book. Currently, it is hard coded to "Test" which isn't quite what I would want in production. :-)

Thanks

Alan

**Comment by DisplayMonkey** [comment]
Hi, we have identified this as a problem in the code. It will be addressed shortly. Please stay tuned.

**Comment by jaschrock** [comment]
great - thanks!

**Comment by DisplayMonkey** [comment]
This has now been fixed as of v1.5.2. There is a new optional field in the Outlook frame now.
