### ISSUE TITLE
Max Recurrence Interval not workign

### ISSUE THREAD

**Issue by hitzand** [fuel9/DisplayMonkey#27]
According to the documentation for Full-screen panels:
> A Max recurrence interval may be set on the Full-screen Panel to limit the number of seconds before the presentation should go into Full-screen mode.

However, when we tried to use this to switch our displays over to a full-screen video, it did not work.  For example, if we set it to 60s, we would notice that the display would go all black shortly after a minute later, like it was going to change to the full-screen video, but then it would quickly re-load the regular multi-panel view.  

We could only get it to switch to full screen by reducing the frame times on the other panels so that the maximum was 5 minutes.  After 5 minutes, the display did correctly switch to full screen and stay on that for the duration set in the full-screen frame (which, even without Max Recurrence Interval, really is a cool feature!)

**Comment by psined1** [comment]
Hi, what kind of content are you loading into the fullscreen frame?

**Comment by psined1** [comment]
Closed as inactive
