### ISSUE TITLE
Problem with Database

### ISSUE THREAD

**Issue by robertocastroserantes** [fuel9/DisplayMonkey#3]
Hello, I found 2 bugs with Database.

If you run anyone of the SQL Files to create the database, is there a problem with the foreign keys. If you want to delete a Canvas that is related to a Display, the program return a SQL Error.

And if you run the SQL Script without demo data, there is a problem with the Dashboard, that fails until you  insert one thing of each type.

Thank you very much for your software.

**Comment by psined1** [comment]
Hi, thank you for reporting an issue with our product. We will review and respond as soon as we can. In the meantime, if you could please provide more details about errors (screenshots, exact error message) as well as steps you followed when you got the errors that would be very helpful. Thanks for giving DisplayMonkey a try!

Fuel9 team

**Comment by DisplayMonkey** [comment]
Fixed in 1.3.1
