### ISSUE TITLE
Japanese dates in datepicker control on google chrome

### ISSUE THREAD

**Issue by HansKatsman** [fuel9/DisplayMonkey#30]
when running the management modules on a google chrome browser the calendercontrol shows japanese names for the days and months.
This is only on google chrome (IE works fine)
We have this on both of our production servers in the company. local language is dutch and afrikaans

I could not reproduce the problem when running the project direct from visual studio in Chrome,
Then it displays without a problem and shows english dates
Thanks Hans Katsman

**Comment by HansKatsman** [comment]
![image](https://user-images.githubusercontent.com/33599319/32967062-7adef704-cbdc-11e7-850a-9b7aefde4f28.png)
problems start when using regional format in Dutch or African

**Comment by DisplayMonkey** [comment]
Hi, thank you for reporting the issue. We will investigate. In the meantime, could you please advise if the issue only manifests itself in Chrome, or in other browsers also?

**Comment by HansKatsman** [comment]
HiThanks for checking The problem is also in ie when using English - South Africa Or English -nl So when you go to a Dutch or African regional format it has this problem 
		
		

		Regards Hans Katsman (mobile)
	




On Mon, Nov 20, 2017 at 4:32 PM +0100, "Display Monkey" <notifications@github.com> wrote:












Hi, thank you for reporting the issue. We will investigate. In the meantime, could you please advise if the issue only manifests itself in Chrome, or in other browsers also?

**Comment by DisplayMonkey** [comment]
OK, thanks again. We will look into this. Meanwhile, since you have previously contributed code to address other issues, would it be fair to assume that you may have done your own investigation as to what could be wrong with the date format? If so, can you share your findings please?

**Comment by HansKatsman** [comment]
last week I investigated, however the problem does not exists if you run with the debugger. Not in IE and not in Chrome. Only when you run from the webserver it shows the japanese dates or gives you a warning about wrong dateformat or if you type a number.
The proper translations are taken and the proper format is taken from the calendar control itselves.
It's on our list to analyze deeper this week.

**Comment by HansKatsman** [comment]
we were able to solve the problem in our fork  https://github.com/TronoxBotlek/DisplayMonkey
