### ISSUE TITLE
Wrong Display at locations

### ISSUE THREAD

**Issue by jaschrock** [fuel9/DisplayMonkey#32]
I have around 20 conference rooms that are being put into production. The first 11 went without a hitch, but my conference rooms 12-15 are all showing the same content as conference room 11. All share the same canvas but have different locations set up and different outlook calendar frames set (each with the correct designated location and unique mailbox). It also isn't just the calendar that is wrong, the whole title is wrong. I also looked in the database to see of anything obvious and don't see anything there. I can't see what is wrong. 

We are on v.1.5.2.162. 

Attached are some screenshots for room 12 (which shows 11 instead of 12). 

Thoughts on where to look next? 

Alan
![locationinfo](https://user-images.githubusercontent.com/24418146/33779366-42c3e226-dc12-11e7-9d39-29b1860b2ae1.JPG)
![outlooksetup](https://user-images.githubusercontent.com/24418146/33779367-42d39950-dc12-11e7-9257-46495d0a370e.jpg)
![roomdisplay](https://user-images.githubusercontent.com/24418146/33779368-42e75328-dc12-11e7-8351-4a66c1f4330f.jpg)

**Comment by amollentze** [comment]
Hi! Have you checked the ip addresses, and that the startup page does not
point to another display but the viewer homepage?

**Comment by jaschrock** [comment]
I have set up one of the "frames" - not sure what that base unit is called on a different machine (my local machine) with the exact same results. So, it doesn't seem to be the computer with the wrong frame. When I look at the registered displays and click on the link for that display it comes up with the Conference Room 11 look as opposed to the correct one. When I click the other ones, they show correctly.

**Comment by jaschrock** [comment]
I don't know how I missed this, but I found that my 11 conference room didn't have a designated location. So, that was making a shared element for all of the rest of them. I am uncertain why it didn't do it for all and not just the later conference rooms, but it is now fixed. 

Thanks
