### ISSUE TITLE
Translate in french

### ISSUE THREAD

**Issue by ACANEXIA** [fuel9/DisplayMonkey#35]
Hello,

I would like to change the text in French, but I don't know how. Is there a solution ?

Thank you.

Jérémy

**Comment by psined1** [comment]
Hi, I believe you refer to DM UI labels/captions translation from English to French, correct? Or did you mean frame text contents? Please clarify. 

The frame content is already at your full control. You can create frames content in any language you want.

If what you mean is UI labels, it is certainly possible as well. However, it is not plug-and-play, and requires recompiling the binaries of the solution. You can contribute translations in other languages to the project by submitting a translated copy of [Resources.resx](https://github.com/fuel9/DisplayMonkey/blob/master/Language/Resources.resx) XML file to [info@displaymonkey.org](info@displaymonkey.org), or simply post it here in this thread and the DM dev team should be able to stick it into next release. 

You only need to translate the text inside the "value" element of the "data" elements. Leave the "name" attribute of "data" elements as is (it is an internal key). You do not need to translate everything - the values you choose not to translate will fall back to default English. 

Once the new language resource pack is distributed with the entire solution, the language will be automatically sensed by the locale settings of your browser. 

Hope this helps.

**Comment by ACANEXIA** [comment]
Hello,

thank you for your reply.

Here is the file "Resources.resx" translate in french : 

[Resources.resx.zip](https://github.com/fuel9/DisplayMonkey/files/1689638/Resources.resx.zip)

I hope it will be in the next update.

Thank you
