### ISSUE TITLE
PowerBI detailed documentation

### ISSUE THREAD

**Issue by FrankDaze** [fuel9/DisplayMonkey#39]
Hi,

I like to use DisplayMonkey to display PowerBi charts in our office. 
But I have some trouble to make an Azure Account inside DisplayMonkey. 
I always get the errors message that my username or password is not valid. 
With the same credentials I can login into my PowerBi account. 

I tried to follow the instructions for generation a new app inside the Azure backend but the screenshots on the instructions page looks different to the pages that I see. And I'm not shure how the PowerBi links should look like to display them inside DisplayMonkey. 

Is it possible to get a more detailed example? 

I need to know is the needed login URL this one: https://app.powerbi.com
And how looks like the redirect URL? Like this: https://app.powerbi.com/redirect 

Where can I enter the URL to the specific chart that I want to display? 

thanks in advance
Frank

**Comment by psined1** [comment]
Hi, you may want to check with [Creating Azure Account](http://www.displaymonkey.org/dm/documentation/other/microsoft-azure-account/) documentation online. Also, depending on how DM is configured in your environment, you may want to check with [Advanced settings](http://www.displaymonkey.org/dm/documentation/application-settings/) documentation to chose the Encryption Mode that best fits your case.

**Comment by psined1** [comment]
Closed as inactive
