### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by ekaramitsos** [fuel9/DisplayMonkey#40]
Hi, I am having an issue across both the presentation and management applications.  On the presentation application, I see a name reference to displaymonkeyDB in the web.config however your instructions say the DB should be called "displaymonkey".  When I launch the presentation url, I do see the webpage and header, but also the error "Object reference not set to an instance of an object.".  Can you breakdown the composition of the web.config connection string?  What could be the cause for this error?

A second issue I am having is with the Management application, where it simply gives me an IIS runtime error.  I am seeing in the web.config a reference to "displaymonkeyentities", but there is no mention in your documentation as to whether this is the DB or instance name.  Kindly advise.

Thanks.

**Comment by ekaramitsos** [comment]
Ok, just an update.  I downgraded SQL to 2016 and fought with IITS, and now I am up and running.  Presentation is working with the dummy data.  Very sleek. However, I cannot use the Management interface.  I am getting an error "Resource was not found".  See the attached screenshot.
![dmm](https://user-images.githubusercontent.com/7862283/37544406-3f82fdf6-293b-11e8-9d87-c9b5dbf6d363.png)

**Comment by Hitenp29** [comment]
Hi am getting the same error 

Object reference not set to an instance of an object.

How did you resolve this ?

Also my management interface doesnt work either and i get the below : 

Server Error in '/DisplayMonkey_Management' Application.

Any help or pointers would be appreciated please.
Thanks
H

**Comment by ekaramitsos** [comment]
@Hitenp29 I did not pay close enough attention to the XML connection string.  I'm running both the SQL server and both the presentation and management interfaces on the same box for testing, so I had to set the data source to the computer name and instance name, thus "data source=WIN-DMSVR\SQLEXPRESS".  It worked fine after then but I still had issues with the management interface.  I tried a number of things but could not get it working, so I just redid the VM as a 2016 Server with SQL Express (2016) and it worked fine following the instructions.  Also, within IIS, don't forget to turn on "Windows Authentication" for the management application. 
![iis](https://user-images.githubusercontent.com/7862283/37658858-e10e06e8-2c24-11e8-8e0d-b0b303e08552.png)

**Comment by Hitenp29** [comment]
Thanks for your reply. I think im going to have to start from scratch, im now getting the :

![capture](https://user-images.githubusercontent.com/37581752/37662809-cc1fc49e-2c4f-11e8-9bdb-d696ceb4e1a6.JPG)

Whereas i was getting the DisplayMonkey page before but with the Object reference not set to an instance of an object. error.

Looks straight forward but the instructions arent brilliant.

Thanks

**Comment by ekaramitsos** [comment]
@Hitenp29 For 0x80070021, try to turn on "HTTP Activation" under Windows Features -> .NET Framework 4.6 Advanced Services -> WCF Services -> HTTP Activation, and restart the websites.

**Comment by psined1** [comment]
Hi, please advise if this can now be closed

Thanks,
DM team

**Comment by Hitenp29** [comment]
Yes please close all resolved.

Regards,
Hiten

**Comment by psined1** [comment]
closed per OP
