### ISSUE TITLE
Traduction error

### ISSUE THREAD

**Issue by ACANEXIA** [fuel9/DisplayMonkey#42]
https://github.com/fuel9/DisplayMonkey/blob/a53461d4af617b8f2eebf3c10157076927a70ab3/Language/Resources.fr.resx#L1490

There is a traduction error. The correct value is : 

<value>La ressource n'est pas disponible pour être réservée</value>

**Comment by psined1** [comment]
Hi, sorry, you lost me - the current value in the resource file appears to equal your corrected value. What am I missing?

**Comment by ACANEXIA** [comment]
Hi,
no problem. Instead of "**Le** ressource...", it must be "**La** ressource..."
It's a french particularity of gender
Thank you

**Comment by psined1** [comment]
Oh, sorry, I've missed that. Will correct in the nearest bug fix. Thanks for noticing.
