### ISSUE TITLE
Error when i try to connect to the the management page

### ISSUE THREAD

**Issue by ACANEXIA** [fuel9/DisplayMonkey#43]
Hi,
with the last update, i have this error when i try to connect to the management page :

![error displaymonkey](https://user-images.githubusercontent.com/35692939/37967696-71bb31aa-31cc-11e8-964c-003aeb2df694.PNG)

When i use the old DLL : "Newtonsoft.Json.dll", it works.

Thank you

**Comment by psined1** [comment]
Did you download and install update from the official [DM portal](http://www.displaymonkey.org/dm/download/)?

**Comment by ACANEXIA** [comment]
yes

**Comment by psined1** [comment]
Well, it's hard to tell without peeping over into your installation. This error looks uncommon as we haven't seen anyone else reporting it, so you must have either done something wrong as you went installing DM or got an unorthodox web server setup. If this is still an issue for you to this moment, then I would suggest you to wipe and re-install DM from scratch and then see what happens.

**Comment by psined1** [comment]
closing issue as stale
