### ISSUE TITLE
Just Black Canvas

### ISSUE THREAD

**Issue by borislaw89** [fuel9/DisplayMonkey#45]
As an Output I just get an black canvas. If I change the background of the canvas (picture or background colour) there's no effect. No Panels as well.

Any ideas? Or paid support? I've written 2 mails but no reaction...

**Comment by jre08** [comment]
I’m having the same problem as well.   The address bar has getdisplay.aspx?display=1 but the page is just white/blank.   I’ve set panels frames and canvases.   The frame is suppose to be a clock.
