### ISSUE TITLE
No events today

### ISSUE THREAD

**Issue by jjchaos** [fuel9/DisplayMonkey#48]
I've added an Office 365 account and setup a frame to display the events, but I'm not seeing events listed even though they exist on the account's calendar. I have it set to show 10 events. Not having any luck.

**Comment by psined1** [comment]
Hi, EWS can be flaky at times. I urge you to begin with troubleshooting from the point of registering Exchange account in DMM under EWS tracing path setting activated (read [here](http://www.displaymonkey.org/dm/documentation/application-settings/)).

With nothing eye catching revealed in the trace, see if your frame is able to resolve mailbox resource name as defined in Exchange and print it at the tope. For that, clear the Name field on the calendar frame setting to let it automatically resolve from the Exchange account.

If your calendar frame calls for mailbox different than that defined in your Exchange account, make sure the calendar is shared properly in the Exchange.

Are all events on the calendar public? If not, make sure "Private" drop-down and "Show As" checkboxes all have proper values set on your calendar frame.

If your DMP server time zone is different from that of your calendar mailbox default time-zone, some events may be excluded. 

Unfortunately, there is no straight recipe to your issue. There may be hundreds of reasons why the calendar is not pulling right. Keep researching and experimenting. Try a simple case, when the EWS account and frame mailbox are the same. Try a different EWS account/mailbox, etc. It appears to work for most people here.

If you have specific questions, don't hesitate. Good luck!

**Comment by psined1** [comment]
OP: were you able to resolve your problem?

**Comment by psined1** [comment]
No response from OP for a while. Closed.
