### ISSUE TITLE
Error logging?

### ISSUE THREAD

**Issue by janicedawley** [fuel9/DisplayMonkey#55]
I'm trying to determine what isn't working with my connection to our SSRS report server, and I'm stumped as to how I can diagnose the issue. The "Report Server Accounts" area in the management console doesn't appear to do any validation of the configuration, so I can't tell if there is a connection or login problem.  And when I add a frame with a link to a report, I get a question mark preview icon, but no error message. On the actual display, all I see is a broken image icon with the "alt text" name of the frame.

Is there any optional logging I can turn on to try to figure out what is happening? Or something already available that I just can't find in the documentation?

**Comment by michaelmalmgren** [comment]
Yes, see the "Error Pop Up" section here http://www.displaymonkey.org/dm/documentation/display/

**Comment by janicedawley** [comment]
We already have that value set to 60 seconds. The problem is that no error is displaying for the SSRS panel. Only a broken graphic.

**Comment by psined1** [comment]
Sounds like this maybe a security issue on the SSRS side. Please check SSRS logs. More details here - 

[Locate SSRS Log Files](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/6bf2a4c9-f652-4c99-972b-75ba9d9447c2/locate-ssrs-log-files?forum=sqlreportingservices)

**Comment by psined1** [comment]
Also, after you create SSRS frame in DMM, you should be able to see report preview in there. Can you see it?

**Comment by janicedawley** [comment]
I looked in the SSRS logs, and there is nothing there to indicate that the DisplayMonkey Presentation application is connecting to the server at all. When I browse to the report manually using the credentials I've entered into the connection, I do see an entry in the log. To me, this indicates that there is a problem with the format of the base url or report url itself, such that DM isn't trying to go the right place.

Re: the preview -- no, it doesn't work. It's just a white question mark inside a red circle.

**Comment by psined1** [comment]
Before you are successful with presentation, you want to make sure you can get preview of the frame in DMM after registering it. Check SSRS report permissions and make sure the account in DMM settings can access the report. If you are able to open the report by going to SSRS reportserver portal directly (not via SharePoint), then you should be able to preview it with DMM as well given the same account as interactive one. Give it a world with different SSRS accounts in DMM settings.

**Comment by janicedawley** [comment]
As I mentioned in the other issue thread (about base urls), I have already confirmed that the user account has permission to access the report. It can open it without issue in a browser window that has been launched on the same server that hosts the DisplayMonkey web applications. I understand that it "should" work in DisplayMonkey, but it doesn't. And I can't seem to find any diagnostic information anywhere to tell me what is going wrong. I've tried many variations on the base url and report url, with no luck. I am really at a loss as to what to do next.

**Comment by psined1** [comment]
Make sure you are testing report without parameters at first.
Open DM database, got to ReportServer table and jot down the SSRS base URL.
After registering your SSRS frame, got to Reports table and snatch the Path value.
Put both pieces together as follows -

{base URL path}?{report path}&rs:format=IMAGE

Copy resulting URL to a new browser window and see what gives.

**Comment by janicedawley** [comment]
I did that with the SharePoint-hosted version of the report, and the browser prompted me to "open" the resulting TIFF image, which displayed without a problem in Windows Photo Viewer. Attempting this with the native mode server didn't work -- I was instead redirected into a "browse" view of the report server. Maybe this relates to the fact that these servers are running different versions of SSRS? (SharePoint mode is version 2014, and the native mode server is 2016.)

**Comment by psined1** [comment]
Well, it is a little hard to suggest much while not knowing your full setup. The goal is to make sure your SSRS report shows properly when directly called from SSRS portal. SP-hosted reports will not run in DM as DM does not support SharePoint security model. So the following canonical URL form is supported by DM and should work -

http://<yourSsrsHost>/reportserver?/yourReport&rs:format=IMAGE

Check this link - [URL Access (SSRS)](https://docs.microsoft.com/en-us/sql/reporting-services/url-access-ssrs?view=sql-server-2017)

**Comment by janicedawley** [comment]
OK! I finally got it working connecting to the native mode server. The issue was that I didn't realize there was a different URL for the web portal vs. the URL access method. I was using "http://server/Reports" instead of "http://server/Reportserver".

Of course, now we have to do some reformatting of that report, because the image export doesn't look right AT ALL. But at least we now have a working connection. Thanks for the help, Denis!

**Comment by psined1** [comment]
http://server/reports is for SSRS management portal, whereas http://server/reportserver is actually for accessing reports in native mode

I'm glad I was able to help. Enjoy DisplayMonkey!

**Comment by psined1** [comment]
You may be able to tweak your report appearance with frame render mode, i.e. crop/stretch/fill, etc.

Mind you that DM SSRS report frames are only limited to the first page of the report. Therefore, if your report spans multiple pages, it is only possible to render the first page. This is by DM design - to provide minimalistic view of reports without navigation controls.
