### ISSUE TITLE
Tips on display size settings

### ISSUE THREAD

**Issue by RBSTAN** [fuel9/DisplayMonkey#56]
Good morning,

We have just implemented DisplayMonkey in the hopes of using it instead of suppliers such as ViewNeo.

It looks like it will do everything we need it too. The only issue we have is that on our demo display screen, we always seem to have trouble getting the entire image we have uploaded to fit on the screen. We've tried various file sizes, crop/fill/fit, etc.

I'm not sure what we're doing wrong with the canvas or display size but it makes our simple images look a bit rubbish...

**Comment by michaelmalmgren** [comment]
Hi, both the fit and fill option should render images in the correct aspect ratio. Can you maybe snap a picture of the display to give us a better idea what it looks like? Please include your specific frame settings.

/M

**Comment by psined1** [comment]
OP: were you able to overcome your problem?

**Comment by RBSTAN** [comment]
Hi everyone, thank you for the replies.

I think the trouble is that I was doing the testing on a screen in our office and the screen in the final location was a different size again.
I kind of got it looking okay by creating a panel/frame of a specific size and ensuring the image we wanted to use was the same size exactly. There's a bit of a border around it but it looks okay.
I'll catch up with the users who asked us to get it live and see if they want me to try and tidy it up. If so, I'll put the frame sizes, etc up in the hope someone can see where I've gone wrong!

**Comment by psined1** [comment]
Closed per OP
