### ISSUE TITLE
PowerBI frame renders (when trying to delete) but does not render in presentation

### ISSUE THREAD

**Issue by overdrive55** [fuel9/DisplayMonkey#57]
I was able to successfully connect to powerbi (through azure setup..etc). 
I added 1 canvas, 1 panel, one powerbi frame.  I noticed that when I try to delete the frame, the page asks me for confirmation and renders the powerbi report correctly on the side. (See picture2). Both Management and presentation are running on the same pc.
When I try to register and select the monitor, it show me this error : 
![image](https://user-images.githubusercontent.com/25217882/43556182-7529fee8-95cc-11e8-93a7-2164052548c1.png)

with the power bi logo coming in and out but nothing else. 

Picture 2
![image](https://user-images.githubusercontent.com/25217882/43556334-4286e130-95cd-11e8-9979-fa6bd4634ea1.png)

**Comment by psined1** [comment]
OP: were you able to overcome your issue?

**Comment by psined1** [comment]
No response from OP for a while, closed.
