### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by daanzii** [fuel9/DisplayMonkey#58]
I'm trying to set up this Digital Signage software for the company I work for but I ran into an error and I'm unsure on the next steps to get around it, The error is as following:

![2018-08-02_13-19-41](https://user-images.githubusercontent.com/28540662/43583393-50e961c8-9657-11e8-8397-ebbbbd7e4727.png)

I followed the steps given and made a DisplayMonkey user in Server Management Studio but it didn't work so I went about trying to make another two users but didn't work either, I gave them db_owner permissions.

![mstsc_2018-08-02_13-26-09](https://user-images.githubusercontent.com/28540662/43583648-0ad22336-9658-11e8-8fd2-28331259eb60.png)

I edited the web.config file for both DisplayMonkey_Management and they have the same details in them and I have them as the following:

![mstsc_2018-08-02_13-31-06](https://user-images.githubusercontent.com/28540662/43583854-a0618b12-9658-11e8-895a-c146d8469601.png)

At this point I was slowly losing hope and had no idea what to do, I added a new user in the server rather than the database with a password (as shown above) and user mapped it to the DisplayMonkey database, Seen below:

![mstsc_2018-08-02_13-35-56](https://user-images.githubusercontent.com/28540662/43584004-121f8e52-9659-11e8-84c9-7c2ae8925f75.png)

I'm completely out of ideas, I'm using Windows Server 2012, Not sure if it's something I haven't configured properly or if it's something I haven't installed in Server manager/Roles and features.

Thanks.

**Comment by michaelmalmgren** [comment]
Hi, can you confirm that you created applications using an application pool with the correct .Net version? See step 2 of the installation instruction for more details http://www.displaymonkey.org/dm/documentation/installation/

Cheers,
/M

**Comment by psined1** [comment]
Check out closed issue #59. See if it will give you any clues.

**Comment by psined1** [comment]
closed per OP
