### ISSUE TITLE
Install Errors

### ISSUE THREAD

**Issue by BobbyOfWindsor1974** [fuel9/DisplayMonkey#59]
![2018-08-07_13-54-31](https://user-images.githubusercontent.com/42067096/43834382-e7c9b2ae-9adb-11e8-8029-4b6a2c3b5dbd.jpg)
I'm trying to install Display Monkey and getting errors:

Server Error in '/DisplayMonkey_Management' Application.
Runtime Error
Description: An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed. 
Details: To enable the details of this specific error message to be viewable on the local server machine, please create a tag within a "web.config" configuration file located in the root directory of the current web application. This tag should then have its "mode" attribute set to "RemoteOnly". To enable the details to be viewable on remote machines, please set "mode" to "Off".
http://localhost/DisplayMonkey_Management
Notes: The current error page you are seeing can be replaced by a custom error page by modifying the "defaultRedirect" attribute of the application's configuration tag to point to a custom error page URL.
AND:
http://localhost/DisplayMonkey/Account/Login.aspx?ReturnUrl=%2fDisplayMonkey%2f
Server Error in '/DisplayMonkey' Application.
The resource cannot be found.
Description: HTTP 404. The resource you are looking for (or one of its dependencies) could have been removed, had its name changed, or is temporarily unavailable. Please review the following URL and make sure that it is spelled correctly. 
Requested URL: /DisplayMonkey/Account/Login.aspx
Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.7.2558.0

**Comment by psined1** [comment]
Hi, could you please verify that 1) DMM web application has Windows Authentication enabled, and 2) DMP has Anonymous and Forms Authentication enabled?

**Comment by BobbyOfWindsor1974** [comment]
For the management side:

[cid:image001.png@01D42E56.3F8BAAD0]



Thanks

--Bobby


Robert Hicks | Senior Technical Analyst, Schukra - Leggett & Platt Automotive Group- North America
360 Silvercreek Industrial Dr., Lakeshore, ON N8N 4Y3 | •: 519-727-7000 Ext. 1003 | :  519-817-1576 |  7: 519-727-7068| •: bobby.hicks@leggett.com<mailto:bobby.hicks@leggett.com>
Website: www.leggett-automotive.com [Description: Description: facebook tiny] <https://www.facebook.com/LeggettAuto>   [Description: Description: insta tiny] <https://www.linkedin.com/company-beta/9362272>   [Description: Description: linked in tiny] <https://www.linkedin.com/company-beta/9362272>   [Description: Description: twitter tiny] <https://www.twitter.com/leggettauto/>
P Please consider your environmental responsibility before printing this e-mail

**Comment by psined1** [comment]
Sorry, your picture did not attach, please use Github website to post your picture.

**Comment by BobbyOfWindsor1974** [comment]
Hi, the picture is now attached. I have made progress, but I am getting this error on the management part.


An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
--
[ArgumentException: Keyword not supported: 'server'.]
   System.Data.Entity.Core.EntityClient.Internal.DbConnectionOptions.ParseInternal(IDictionary`2 parsetable, String connectionString, IList`1 validKeywords) +422
   System.Data.Entity.Core.EntityClient.Internal.DbConnectionOptions..ctor(String connectionString, IList`1 validKeywords) +120
   System.Data.Entity.Core.EntityClient.EntityConnection.ChangeConnectionString(String newConnectionString) +165
   System.Data.Entity.Internal.LazyInternalConnection.InitializeFromConnectionStringSetting(ConnectionStringSettings appConfigConnection) +111
   System.Data.Entity.Internal.LazyInternalConnection.TryInitializeFromAppConfig(String name, AppConfig config) +39
   System.Data.Entity.Internal.LazyInternalConnection.Initialize() +161
   System.Data.Entity.Internal.LazyInternalConnection.get_ProviderName() +16
   System.Data.Entity.Internal.DefaultModelCacheKeyFactory.Create(DbContext context) +132
   System.Data.Entity.Internal.LazyInternalContext.InitializeContext() +713
   System.Data.Entity.Internal.InternalContext.Initialize() +26
   System.Data.Entity.Internal.InternalContext.ForceOSpaceLoadingForKnownEntityTypes() +42
   System.Data.Entity.DbContext.System.Data.Entity.Infrastructure.IObjectContextAdapter.get_ObjectContext() +31
   DisplayMonkey.Models.Setting.Initialize(DisplayMonkeyEntities _db) +59
   DisplayMonkey.MvcApplication.Application_Start() +277

[HttpException (0x80004005): Keyword not supported: 'server'.]
   System.Web.HttpApplicationFactory.EnsureAppStartCalledForIntegratedMode(HttpContext context, HttpApplication app) +535
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +166
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +169
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +372
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +329

[HttpException (0x80004005): Keyword not supported: 'server'.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +525
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +118
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +708

**Comment by psined1** [comment]
Didn’t run into this error before? Did you mess with connection string under web.config? DMM uses Entity Framework and DMP uses ADO.Net. Check this link -

https://stackoverflow.com/questions/6646833/keyword-not-supported-server

**Comment by BobbyOfWindsor1974** [comment]
I just added the connection strings from the Connection ICON.  The front end works.  The backend management is the one that's giving me the issues now.

**Comment by BobbyOfWindsor1974** [comment]
The install shows an image.  I modified the web.config in the Display_Mananagement folder and I still get an error.

**Comment by BobbyOfWindsor1974** [comment]
I think I have it.

<add name="DisplayMonkeyEntities" connectionString="metadata=res://*/Models.DMModel.csdl|res://*/Models.DMModel.ssdl|res://*/Models.DMModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=.\SQLEXPRESS;initial catalog=DisplayMonkey;persist security info=True;user id=DisplayMonkey;password=Supermonday1;MultipleActiveResultSets=True;App=EntityFramework&quot;" providerName="System.Data.EntityClient" />

**Comment by psined1** [comment]
OK great! I’ll close the issue for now.

**Comment by R-a-b** [comment]
Bobby, I have the same/similar issue.  How did you resolve it ?
Thanks
Chris

**Comment by BobbyOfWindsor1974** [comment]
Sorry, it’s been a while. What’s the specific error?



Thanks

--Bobby


Robert Hicks | Senior Technical Analyst, Schukra - Leggett & Platt Automotive Group- North America
360 Silvercreek Industrial Dr., Lakeshore, ON N8N 4Y3 | •: 519-727-7000 Ext. 1003 | :  519-817-1576 |  7: 519-727-7068| •: bobby.hicks@leggett.com<mailto:bobby.hicks@leggett.com>
Website: www.leggett-automotive.com [Description: Description: facebook tiny] <https://www.facebook.com/LeggettAuto>   [Description: Description: insta tiny] <https://www.linkedin.com/company-beta/9362272>   [Description: Description: linked in tiny] <https://www.linkedin.com/company-beta/9362272>   [Description: Description: twitter tiny] <https://www.twitter.com/leggettauto/>
P Please consider your environmental responsibility before printing this e-mail

**Comment by R-a-b** [comment]
Thanks for getting back to me.

It's to do with configuring DisplayMonkey.

I've created the database and user in SQL and modified the 2 web.config files as per the instructions, but am getting a SQL error message  on the web page - Login failed for user 'DisplayMonkey'

From your comments - this is what you were getting too (or something very similar), but then you said you'd resolved it, I was just wondering if you can remember how you did it.

Cheers mate.

Chris


________________________________

**Comment by BobbyOfWindsor1974** [comment]
Anytime.

Connection Settings from IIS:

[cid:image001.png@01D4CE8C.89C66190]

Web Config:

  -->
<configuration>
  <configSections />
  <connectionStrings>
        <remove name="LocalSqlServer" />
    <add connectionString="Server=SWSR0102\SQLEXPRESS;Database=DisplayMonkey;User ID=DisplayMonkey;Password=xxxxxxxxx" name="DisplayMonkeyDB" providerName="System.Data.SqlClient" />
        <add connectionString="Server=SWSR0102\SQLEXPRESS;Database=DisplayMonkey;User ID=DisplayMonkey;Password= xxxxxxxxx " name="LocalSqlServer" providerName="System.Data.SqlClient" />
  </connectionStrings>


Thanks

--Bobby


Robert Hicks | Senior Technical Analyst, Schukra - Leggett & Platt Automotive Group- North America
360 Silvercreek Industrial Dr., Lakeshore, ON N8N 4Y3 | •: 519-727-7000 Ext. 1003 | :  519-817-1576 |  7: 519-727-7068| •: bobby.hicks@leggett.com<mailto:bobby.hicks@leggett.com>
Website: www.leggett-automotive.com [Description: Description: facebook tiny] <https://www.facebook.com/LeggettAuto>   [Description: Description: insta tiny] <https://www.linkedin.com/company-beta/9362272>   [Description: Description: linked in tiny] <https://www.linkedin.com/company-beta/9362272>   [Description: Description: twitter tiny] <https://www.twitter.com/leggettauto/>
P Please consider your environmental responsibility before printing this e-mail

**Comment by R-a-b** [comment]
Cheers mate, all sorted, thanks again for the quick response.

**Comment by BobbyOfWindsor1974** [comment]
No worries.  Glad to help

Sent from my iPhone

On Feb 28, 2019, at 5:21 AM, R-a-b <notifications@github.com<mailto:notifications@github.com>> wrote:


Cheers mate, all sorted, thanks again for the quick response.
