### ISSUE TITLE
YouTube AutoLoop

### ISSUE THREAD

**Issue by ehuels-zahner** [fuel9/DisplayMonkey#60]
I assume the AutoLoop setting for YouTube video is intended to restart the video for as long as the fram duration is set.  If this is correct, then it doesn't appear to be working.  Turning the AutoLoop option on/off has no impact to the video.

Am I missing something?

**Comment by michaelmalmgren** [comment]
As I understand it the Auto Loop option will loop any YouTube video during the entire duration of the frame e.g. if your frame is visible for 3 minutes and the YT video is 1 min long it will be shown three times with the Auto Loop option set to on. In the off setting it will be shown once, nothing will then be shown for the remaining 2 minutes.

**Comment by ehuels-zahner** [comment]
Yes, that is what I am trying to do.  The video is about 15 seconds long and I have the frame duration set to 60 seconds. The video plays once and then stops.  Toggling the Auto Loop has no effect.

**Comment by michaelmalmgren** [comment]
I see what you’re saying and I was able to reproduce this behavior in v.1.6.0.182.
