### ISSUE TITLE
Upload file size

### ISSUE THREAD

**Issue by Karhl** [fuel9/DisplayMonkey#61]
I've set the max upload size for pictures to around 50mb
When uploading even a 200kb jpeg, it alerts me that the max filesize is 50mb and prevents me from uploading.
Any tricks I'm missing?

**Comment by michaelmalmgren** [comment]
Hi Karhl,

I wasn't able to reproduce this. Please note that the file size is expressed in bytes so a 50Mb limit would translate to 50000000 bytes.

**Comment by psined1** [comment]
closed per OP
