### ISSUE TITLE
Fullscreen question

### ISSUE THREAD

**Issue by eileenwrs** [fuel9/DisplayMonkey#64]
I have tried out the default Canvas and Panel with FullScreen. But somehow FullScreen isn't really fullscreen on different browsers even on my Windows 10. Firefox is fullscreen, but Chrome doesn't.
I have also tested on a Minix Android TV Box, using Chrome the fullscreen is only extends to half a screen
How do I get fullscreen to be really fullscreen? 

![fullscreenonandroidbox](https://user-images.githubusercontent.com/31882251/44579368-b4c37f00-a785-11e8-94c9-5bdacc22f056.jpg)

**Comment by tawdanst** [comment]
Is the resolution on the canvas the same resolution as the display it's playing on?

**Comment by eileenwrs** [comment]
I set the canvas to 1920 × 1080, and the recommended resolution for the monitor is also 1920 x 1080. 
Is the difference caused by the different browser rendering on different OS? The image i posted is from the Minix Android box.

**Comment by psined1** [comment]
Hi, thank you for sharing your experience. As of today, no compatibility tests were made on MiniX devices, so I would venture to say you are the first. Going further on advise from
@tawdanst, try fiddling with canvas size and see what happens.

**Comment by psined1** [comment]
OP: have you been able to overcome this issue?

**Comment by eileenwrs** [comment]
i have shelved this effort for the moment, and evaluating other devices.

**Comment by psined1** [comment]
Closed per OP

**Comment by bruno2galdino** [comment]
hey everyone, could anyone solve this problem?
