### ISSUE TITLE
Removing medialess frames

### ISSUE THREAD

**Issue by MichelCote** [fuel9/DisplayMonkey#69]
Hi,

Is there a way to bypass the following error when I want to delete a frame that had it's media previously deleted?

**Requested resource does not exist.

Picture with id# 23 could not be found
Back to previous page**

Thanks
Michel

**Comment by tawdanst** [comment]
Also looking for a fix for this issue

**Comment by moeman2323** [comment]
As am I.

**Comment by psined1** [comment]
Hi, trying to reproduce your error scenario. Could you please describe the steps leading you to the error? Thanks

**Comment by tawdanst** [comment]
1. Upload picture
2. Put picture into a panel as a frame
3. Delete picture in media gallery
4. Try delete frame with image inside 
5. Error

**Comment by MichelCote** [comment]
Yes, exactly as described by tawdanst.

**Comment by psined1** [comment]
OK, thanks
