### ISSUE TITLE
Deployment to Azure Webapp + SQL

### ISSUE THREAD

**Issue by kamwai** [fuel9/DisplayMonkey#7]
I just setup Azure webapp + SQL and deployed via Github.
I edited the DB connection in web.config and managed to see the Presentation successfully.

However, the Management folder wasn't deployed. I tried to deploy manually but it just won't work.

**Comment by DisplayMonkey** [comment]
Hi, can you provide us a little more detail on how did you manage to deploy please? Is this still an issue?

**Comment by DisplayMonkey** [comment]
no longer an issue with OP: "BTW, I have deployed to Azure webapp via github."
