### ISSUE TITLE
relation between SSRS width and Canvas size

### ISSUE THREAD

**Issue by carntsen1** [fuel9/DisplayMonkey#75]
I am having difficulty figuring out the relation between SSRS report width and Defined panel size. 

Example; 
My panel is full screen (1600x1000). I write a report that is 'normal' paper size and many columns on the right get cut off.  I have to keep reducing the width (and font) until the report is only about 4" wide before it all displays on the screen. 

I thought I might need to set my report page size to match the screen aspect ratio. 1600x1000 would be the same as 8" x 5".  This might the output much worse

Can anyone advise how to properly size a report to the panel? 
Cam

**Comment by michaelmalmgren** [comment]
Hi Cam,

Only the first page in a multi-page report will be shown. What is included on the first page will depend on Interactive Page Size in SSRS. DM will display the report as an image and the options "Fit" should make the entire first page of the report to show. 

/M

**Comment by psined1** [comment]
Another thing to consider is that every SSRS report has page setup under report properties in SSRS designer. I advise you to play with those settings and see if they will have any effect on how report turns out in DM.

**Comment by carntsen1** [comment]
Thank you… I am doing just that this morning.
So far I am finding that while the report may look good on my screen (in report designer), If I select ‘Print Layout’ it exactly matches the DM output with cut off columns.
Getting better quickly as I focus on settings in report designer.

Thanks for your help
Cam

**Comment by psined1** [comment]
Hi, are we all set? Can we close this?

**Comment by carntsen1** [comment]
I think so… output is looking much better now
Thanks

**Comment by psined1** [comment]
Awesome! OP was able to self-assist. Closing.
