### ISSUE TITLE
Error: Object already exists. when displaying Power BI frame

### ISSUE THREAD

**Issue by kamwai** [fuel9/DisplayMonkey#8]
Error:	Object already exists.
Where:	Powerbi::callBack::onSuccess
When:	2017-02-03T01:32:54-08:00
Info:	{Error:Object already exists.\\r\\n,Data:{FrameId:1403,PanelId:119,DisplayId:41,Culture:en-US,Details:null}}

I have managed to get the BI report display once, but after i wipe and reinstall DisplayMonkey, it stops showing the charts now.

**Comment by psined1** [comment]
Hi, greetings from the DisplayMonkey team!

When you reinstall DM you need to keep several things in mind. All passwords in DM are stored in the database as hashes (instead of actual values). A special RSA container is used to scramble and generate those hashes and then decode them back in the application. This RSA container is unique per machine (which runs IIS). 

So, if you re-install or move DM to a different machine, you may want to synchronize the RSA container from the old server (from which the accounts were created) to the new one. The same goes if you change application pool identity for either DMM or DMP application – you must grant RSA container access to another account.

Please refer to "Multi Presentation Server Environment” section of the DM installation page:

http://www.displaymonkey.org/dm/documentation/installation/

The source code distribution of DisplayMonkey on GitHub contains 3 batch files for RSA container management:

grantDmRsaKey.bat
exportDmRsaKey.bat
importDmRsaKey.bat

Alternatively you can try simply re-entering the password on all account records which you have created. This includes PowerBI, Exchange and SSRS accounts.

Hope this helps. Please mind you that we are about to release a minor update to DM in the next few days, so stay tuned.

Thank you for choosing DisplayMonkey!

**Comment by kamwai** [comment]
Hi
I have both management and presentation running on same machine and I have tried setup everything from scratch on a clean server 2012 and on Azure webapp, but the error still seen on both environment.
 
Is it something wrong with power BI embedded code? Other non-BI frames have no problem displaying.

Please let me know if you need more details.

thanks

**Comment by DisplayMonkey** [comment]
Are you using any other frame types which require authentication, such as SSRS report or Exchange calendar? If so, do they work without issues?

In DMM application, when you create PwrBI account, does it save without errors? If so, when you edit an existing PwrBI frame settings, does it pull dashboards/tiles/reports at all?

**Comment by kamwai** [comment]
Hi,


I am not using SSRS or Exchange Calendar. I re-installed everything and HTML frame works so far.


No issue when Create or Edit PowerBI account, under Resource type i tried both Reports and Tiles, but same error message seen.


Under Azure account setting, Tenant id is blank - does it matter?


Please see the attached screen shot, I can see the PowerBI logo loading but it just stay that way

Regards,
Kam Wai

________________________________

**Comment by DisplayMonkey** [comment]
Hi, your PwrBI admin should be able to advise whether or not your organization is using tenants.

**Comment by DisplayMonkey** [comment]
Unfortunately the screenshots did not come attached, could you resend/repost please?

**Comment by kamwai** [comment]
![untitled](https://cloud.githubusercontent.com/assets/25372491/22661122/0b2d28da-ec59-11e6-8dd5-db4319e88721.png)

**Comment by kamwai** [comment]
I have tried setting this up on 3 different systems - Win 2003, Win 2012 & Azure webapp.

Same problem still seen.

**Comment by DisplayMonkey** [comment]
OK, we have released update 1.3.3 this morning. Please install it and I will provide you instructions on how to trace into more details of the error.

**Comment by kamwai** [comment]
nice, will you be updating the binaries in here? http://www.displaymonkey.org/dm/download/

**Comment by DisplayMonkey** [comment]
Yes, if they are not there yet. Give me your email, I'll send you the zip archive otherwise.

**Comment by kamwai** [comment]
sure, please email to kamwai [at] hotmail [dot] com

**Comment by kamwai** [comment]
BTW, I have deployed to Azure webapp via github.

When i tried to add an Azure account, I am getting this error....no problem previously using the last version

_Source	
AzureAccount/Create
Message	
The field IdToken must be a string or array type with a maximum length of '1000'.
Stack trace	
   at DisplayMonkey.Models.DisplayMonkeyEntities.SaveChanges()
   at DisplayMonkey.Controllers.AzureAccountController.<CreateAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)_

**Comment by DisplayMonkey** [comment]
any luck since my last email?

**Comment by kamwai** [comment]
no luck, still the same error and here is the trace


{"Error":"Client ID is required.","Stack":"   at DisplayMonkey.DataAccess.\u003cExecuteTransactionAsync\u003ed__1e.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at DisplayMonkey.Powerbi.\u003cGetAccessTokenAsync\u003ed__11.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at DisplayMonkey.Powerbi.\u003cGetAccessTokenAsync\u003ed__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at DisplayMonkey.getAzureToken.\u003cProcessRequestAsync\u003ed__0.MoveNext()","Data":{"FrameId":1403,"PanelId":119,"DisplayId":41,"Culture":"en-us","Details":null}}



________________________________

**Comment by psined1** [comment]
Please delete and recreate the azure account. Are you making sure to enter Client ID and Client Secret as you save the account?

Thanks // Denis

**Comment by thadspencer** [comment]
REF: "The field IdToken must be a string or array type with a maximum length of '1000'"

I'm getting this when I edit or try and re-create the Azure account.

I've tried resetting the user password, issuing new azure ad app keys, blanking the DM database.

Any ideas of what else to try?

It was working fine then my colleague changed the Azure User's password, then this started :(

**Comment by DisplayMonkey** [comment]
Yes, we are working on the solution right now. Please stay tuned

**Comment by DisplayMonkey** [comment]
Hi @thadspencer, are you working together with @kamwai on the same problem by any chance?

**Comment by thadspencer** [comment]
no, but my situation seems similar

**Comment by DisplayMonkey** [comment]
Please give me your email, I'm going to send you a patch to try

**Comment by thadspencer** [comment]
ts.burn@airinmar.com***

**Comment by thadspencer** [comment]
thank you for the patch - working now 👍 

monkey loves max columns :D

**Comment by kamwai** [comment]
no luck for me, may I know what you have done?


________________________________

**Comment by thadspencer** [comment]
DM mailed me a patch including a couple of binaries and a query to run

**Comment by psined1** [comment]
That’s great! As it appears the Azure token sizes have increased recently, we will release another fix in a day or so. Thanks for your help.

**Comment by thadspencer** [comment]
My pleasure and thank you too, and congratulations on making such awesome software. The D Monkey rocks!

**Comment by DisplayMonkey** [comment]
awaiting @kamwai to confirm that the issue can be closed

**Comment by kamwai** [comment]
No luck, still the same error trace. I have deleted every thing and re-do already

**{"Error":"Client ID is required.","Stack":"   at DisplayMonkey.DataAccess.\u003cExecuteTransactionAsync\u003ed__1e.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at DisplayMonkey.Powerbi.\u003cGetAccessTokenAsync\u003ed__11.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at DisplayMonkey.Powerbi.\u003cGetAccessTokenAsync\u003ed__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at DisplayMonkey.getAzureToken.\u003cProcessRequestAsync\u003ed__0.MoveNext()","Data":{"FrameId":1403,"PanelId":119,"DisplayId":41,"Culture":"en-us","Details":null}}**

**Comment by DisplayMonkey** [comment]
Have not heard back from the OP for over 2 weeks now. Considering the issue closed now?

**Comment by techie-pete** [comment]
I am having the same issue as the orginal poster kamwai.  
_Object already exists. Where:	Powerbi::callBack::onSuccess
{Error:Object already exists.\\r\\n,Data:{FrameId:1440,PanelId:132,DisplayId:45,Culture:,Details:null}}_

I have deleted the Azure account multiple times and successfully added it back.
I have replaced the presentation and the management code with the latest release.
I can traverse my Workspace and see Tiles and Reports to choose for Frames.
I have altered the column in SQL to extend for Azure Token.
I still have the red dialogue pop up every time a PowerBi component first renders on the screen.

Any thoughts?

**Comment by hitzand** [comment]
We are now getting the same error on editing or setting up any new Azure accounts:
_AADSTS90014: The request body must contain the following parameter: 'password'., Trace ID: ......_

**Comment by DisplayMonkey** [comment]
Hi, we have just released an update 1.4.0. Please upgrade and see if it will take care of your issue.

Please note that in this release we have offered an alternative encryption method, to workaround RSA container manageability issues associated with Azure deployment. Please refer to Application Settings paragraph in the DM documentation for more details and examples.

**Comment by DisplayMonkey** [comment]
For Azure deployments please consider the new AES with stored key encryption mode DMM application setting. Once you have selected the new encryption mode, please re-enter passwords for all accounts under application settings in DMM.

**Comment by DisplayMonkey** [comment]
![display_monkey_2__running_](https://cloud.githubusercontent.com/assets/13225024/25970403/21f0c41a-365e-11e7-844e-537ef096bf22.png)

**Comment by DisplayMonkey** [comment]
We are going to close this particular issue for we believe it has been addressed in the latest DM release. If you still have this or similar issue. Please open another ticket. Thanks. 

// DM team.
