### ISSUE TITLE
Message | Invalid column name 'Type'.

### ISSUE THREAD

**Issue by cwhitsbm** [fuel9/DisplayMonkey#81]
Hello,

In addition to the last error I sent, I am also receiving this error when trying to upload media.

Source | Media/Upload
-- | --
Message | Invalid column name 'Type'.
Stack trace | at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)    at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)    at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)    at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)    at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()    at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)    at DisplayMonkey.Models.Setting.GetSetting(DisplayMonkeyEntities _db, Keys _id) in e:\project\DisplayMonkey\Management\Models\SettingKeys.cs:line 200    at DisplayMonkey.Controllers.MediaController.Upload() in e:\project\DisplayMo

**Comment by psined1** [comment]
Sounds like your database may be out of sync from what the application expects. It seems like you may have installed DM previously and upgraded it once or twice and, maybe, didn't follow all the upgrade SQL scripts? Can you shed a bit more light on your case please?

**Comment by cwhitsbm** [comment]
Yes.  This is a brand new installation.  I had just created the users and the database and ran the install.sql script.  From there it directs you to the management page.

This was from a download I performed from the website last week.

We are running IIS and SQL Express 2014 on the same machine under Windows 10.

Thank you,

Chris Whitaker
IT Support Manager
cwhitaker@sbmcorp.com<mailto:cwhitaker@sbmcorp.com>

[cid:3366863269_253469]
O: 916.565.6074
F:  916.565.3679

Discover the SBM difference: www.sbmmanagement.com<http://www.sbmmanagement.com/>

Check us out on  [cid:image003.jpg@01D474DF.A2F8F260] <https://www.linkedin.com/company/sbm-site-services-llc/#a11y-content>

This email transmission and any documents, files or previous email messages attached to it may contain information that is confidential or legally privileged. If you are not the addressee or authorized to receive this message for the addressee, you may not use, copy or disclose to anyone this message or its contents. If you have received this message in error, please notify the sender immediately and permanently destroy any copies you may have.

**Comment by cwhitsbm** [comment]
Solved...  One of my emps did attempt the install before I took over.  Apparently however he did not download the latest and greatest and did not save his download file.  So when I took over and had to re-download the sql scripts, I downloaded the most current and that must be where the mismatch came in.  Thank you for your help.

**Comment by psined1** [comment]
Makes sense! Glad you'd worked it all out!
