### ISSUE TITLE
Clock minutes not chaning 

### ISSUE THREAD

**Issue by Johnbza** [fuel9/DisplayMonkey#83]
I am using the default Clock setup, however, the minutes are not updating. The clock displays the hour correctly but the minute does not change, seems to be stuck at the same minute no matter what time you connect to the canvas. 
 
I have done the following. 

Upgraded my install to v.1.6.0.182. 
Run the SQL Script. 
Tried displaying just the clock without the date.
Changed the duration

**Comment by michaelmalmgren** [comment]
Hi John,

Check to see if minutes are formatted incorrectly i.e. HH:MM rather than HH:mm.
 
mm = minute
MM = month

You can read more here: http://www.displaymonkey.org/dm/documentation/location/

**Comment by Johnbza** [comment]
Hi 

Thank you, This was the issue. Strange as that was there from the beginning.
