### ISSUE TITLE
Yahoo weather API is end of life

### ISSUE THREAD

**Issue by HansKatsman** [fuel9/DisplayMonkey#92]
We found today that the Yahoo weather API is end of life soon.
In our own version we used the weather underground API, however also this API stops Jan1 2019.
Do you know a free alternative? We found a few with limited calls per minute like https://openweathermap.org/appid

**Important EOL Notice
The weather.yahooapis.com and fallback endpoints are being retired. We will no longer be providing free Weather API services for public users. 
Please contact yahoo-weather-ydn-api@oath.com if you have any questions, comments, or interest in supported paid services.**

**Comment by DisplayMonkey** [comment]
This is a tough one. Nobody these days wants to offer weather for free.

Considering this route -
https://developer.yahoo.com/weather/?guccounter=1

**Comment by mtterry** [comment]
https://openweathermap.org has a free version with up to 60 calls per minute.

**Comment by psined1** [comment]
Thanks for sharing, good to know. We will explore this as an option.

**Comment by jre08** [comment]
Take a look at:
https://github.com/michael-lynch/open-weather … 

I combined two scripts to form my own weather using an HTML frame.

https://www.jqueryscript.net/other/jQuery-City-Weather-Forecast-Plugin-with-YQL-WeatherFeed.html  
--and--
https://github.com/michael-lynch/open-weather

**Comment by psined1** [comment]
@jre08 - great to know you've found a workaround. If you could share some details how you have implemented it with DM, that would be great help for other people.

In the meantime we are planning a service release with updated (and still free :) Yahoo API.

**Comment by HansKatsman** [comment]
Thanks
We also implemented the open weather api solution in DecemberI’ll share the link to our code tomorrow 
    	
    	

    	Regards Hans Katsman (mobile)
    
  




On Mon, Feb 11, 2019 at 8:34 PM +0100, "Denis P." <notifications@github.com> wrote:












@jre08 - great to know you've found a workaround. If you could share some details how you have implemented it with DM, that would be great help for other people.


In the meantime we are planning a service release with updated (and still free :) Yahoo API.

**Comment by jre08** [comment]
The following is the code I inserted into an HTML frame.  Of course you will need the script from https://github.com/michael-lynch/open-weather  to implement this.  I did modify the script a little so that it would display a "weather" background picture.  I can go into further detail on how this can be accomplished pretty easily, if anyone is interested.  

`<div class="weather-wrapper hide">
		<div>
		<span class="weather-description capitalize"></span><br />
		<img class="weather-icon" alt="Weather Icon" src="">
		</div>

		
		<div>
		<strong>Temperature:&nbsp;&nbsp;</strong><span class="weather-temperature"></span>
		<br /><strong>Hight:&nbsp;&nbsp;</strong><span class="weather-max-temperature"></span> 
		<br /><strong>Low:&nbsp;&nbsp;</strong><span class="weather-min-temperature"></span> 
		</div>
		
</div>
	<script src="http://Website.Name/jquery/jquery-3.3.1.min.js"></script>
	<script src="http://Website.Name/jquery/openweather/openweather.js"></script>
<script>

		$(function() {

			$('.weather-temperature').openWeather({
				key: 'YOU_API_CODE_FOUND_@_OPENWEAHTER.ORG',
				city: 'YOUR_CITY_NAME',
				units: 'f',
				descriptionTarget: '.weather-description',
				windSpeedTarget: '.weather-wind-speed',
				minTemperatureTarget: '.weather-min-temperature',
				maxTemperatureTarget: '.weather-max-temperature',
				humidityTarget: '.weather-humidity',
				sunriseTarget: '.weather-sunrise',
				sunsetTarget: '.weather-sunset',
				placeTarget: '.weather-place',
				iconTarget: '.weather-icon',
				customIcons: 'http://dddp.apd.fl.local/jquery/openweather/img/icons/weather/',
				success: function(data) {
					// show weather
					$('.weather-wrapper').show();
					console.log(data);
				},
				error: function(data) {
					console.log(data.error);
					$('.weather-wrapper').remove();
				}
			});

		});

	</script>`
