### ISSUE TITLE
Display Public Website

### ISSUE THREAD

**Issue by JimPowersDFL** [fuel9/DisplayMonkey#98]
Hello,

We are using Qless to create "digital lines" so people don't have to come and wait in our lobby for appointments. It will text you and let you know when you should show up. Very cool.

My question, they have a URL we can go to so patrons can see the queue on a display once they arrive on-site. Does anyone know how I might include that URL in a frame? I see an HTML frame type but it apparently wants the raw HTML. I just need to provide a URL for it to pull from, much like SSRS works.

**Comment by henchffs** [comment]
+1 on this one.
It would be amazing if that functionality was added! :)

**Comment by JimPowersDFL** [comment]
I had forgotten I posted this question. I was able to do a workaround, it just isn't ideal. I used an HTML frame with the following code:

<style>
.hide-cursor {
        position: absolute;
        top: 0;
        bottom: 0;
        right: 0;
        left: 0;
        cursor: none;
        z-index: 100;
    }
</style>
<iframe width="1525" height="798" src="[website URL here]"></iframe>
<div class="hide-cursor"></div>

The problem I'm having is that the URL has to authenticate each time it is accessed so it is a little slow. If I'm ONLY displaying this on the target display, it will be fine but if I want to rotate through other items, when it comes back here it has to authenticate again. I'm not sure what the ideal method of display for my use would end up being unless the server could maintain the connection and just take a snapshot of what it looks like just before moving the display to it.

**Comment by psined1** [comment]
The main reason for this not having been implemented is the CORS restriction in most browsers. It is a security measure, which some browsers let you pass on, yet others don't. Authentication is yet another issue in its own - every browser implements it differently. Some allow saving credentials, whereas others will prompt you to death on each and every request. In the roadmap we have a native app to host DMP display, which would allow saving credentials. But that is a long way.

**Comment by JimPowersDFL** [comment]
That makes perfect sense and I'm glad to hear it is on the roadmap even if it is a long way out. Thank you for clarifying!
