### ISSUE TITLE
Please add a new compiled release 1.6.1

### ISSUE THREAD

**Issue by DisplaymonkeyCT** [fuel9/DisplayMonkey#99]

**Comment by DisplaymonkeyCT** [comment]
Is it possible to compile the latest version and add it to the release section?

**Comment by DisplaymonkeyCT** [comment]
compiled

**Comment by DisplaymonkeyCT** [comment]
Thanks, can I get the changed files in another way? We have troubles to get the powerbi tiles displayed..

BR
Huib

Op 21 jan. 2019 om 15:25 heeft Denis P. <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Hi, this is still in QA testing. We are hoping to publish it shortly. Please bare with us. Thank you for your patience.

**Comment by psined1** [comment]
You have indicated that you were able to compile, isn't that so? I believe you should be good in so far.

**Comment by DisplaymonkeyCT** [comment]
Hi,

Got an error on the management website, so reverted unfortunately back to the old version.

BR
Huib

Op 21 jan. 2019 om 17:12 heeft Denis P. <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


You have indicated that you were able to compile, isn't that so? I believe you should be good in so far.
